### ISSUE TITLE
Bridge: connecting wallets (bug)

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-portal#200]
As a new user that wants to use the bridge I must install 2 non-custodial wallets.

- A wallet of my choice for Ethereum (MetaMask)
- A wallet of my choice for Fuel (official Fuel wallet)

Upon successful installation of the wallets I would like to connect the wallets to the bridge.
In order to connect I click the respective "connect \<wallet\>" buttons.

The same pop-up to install wallets comes up because the site has not recognized that I have installed the wallets. In order to make the feature work as expected I had to refresh the page.

Upon refreshing the page clicking the "connect \<wallet\>" button prompted the pop-ups requesting connection and thus behaving as expected.

**Comment by MiXiCon** [comment]
I use https://alpha.fuel.network/bridge?from=eth&to=fuel to bridge between sepolia (MetaMask) and Fuel (Fuel wallet) and it is working now.
