### ISSUE TITLE
Bridging `TKN` from Sepolia to Fuel throws an error.

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-portal#203]
We cannot bridge the `TKN` to Fuel.

When approving the following error occurs so the bridge is stuck.

![1](https://github.com/FuelLabs/fuels-portal/assets/103777923/0898f9b8-fa45-4f14-aed1-fe09f45b1d32)

**Comment by cpp-phoenix** [comment]
Hey. @Braqzen, I can look into it. Please assign it to me

**Comment by Braqzen** [comment]
> Hey. @Braqzen, I can look into it. Please assign it to me

I don't have the permissions to assign anyone in this repository and the team is aware of the issue and given the conversation it's likely to be looked into sometime soon by us.

**Comment by cpp-phoenix** [comment]
@Braqzen, If team is not already working on it can I pick this up?
